server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 让 gateway 通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: between_route
          uri: lb://user-center
          predicates:
            # 当且仅当请求时的时间 Between 配置的时间时，才会转发到用户微服务
            # 因此，访问 localhost:8040/** -> user-center/**
            # eg. 访问 http://localhost:8040/users/1 -> user-center/users/1
            - TimeBetween=上午9:00, 下午5:00
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
            - PreLog=a,b

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
